import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState, useEffect } from 'react'
import { supabase } from '../utils/supabaseClient'
import { Spinner } from '@chakra-ui/react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
    const [menu, setMenu] = useState([])
    const [loading, setLoading] = useState(true)
    useEffect(() => {
        fetchPosts()
    }, [])

    async function fetchPosts() {
        const { data, error } = await supabase
            .from('menu')
            .select()
        setMenu(data)
        setLoading(false)
        console.log(data)
    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.main} ${inter.className}`}>
                {
                    !loading ? (
                        <ul>
                            {
                                menu.map(menuItem => (
                                    <li key={menuItem.id}>
                                        {menuItem.id}
                                        <div className='menu-item-img'
                                            style= {{
                                                backgroundImage: `url(${menuItem.image_url})`,
                                                backgroundPosition: 'center',
                                                backgroundSize: 'contain',
                                                height: '200px',
                                                width: '200px',

                                            }}
                                        >

                                        </div>
                                    </li>
                                ))
                            }
                        </ul>
                    ) : 
                    <Spinner
                        thickness='6px'
                        speed='0.65s'
                        emptyColor='gray.200'
                        color='green.500'
                        size='xl'
                    />
                }
            </main>
        </>
    )
}
